[package]
name = "blockchain-voting-app-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.blockchain-voting-app]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.2"
default-features = false
