// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    blockchain_voting_app
    (
        init => init
        upgrade => upgrade
        addAllowedVoter => add_allowed_voter
        removeAllowedVoter => remove_allowed_voter
        createElection => create_election
        vote => vote
        getElectionResults => get_election_results
        getElectionsMetadata => elections_metadata
        getVotes => votes
        allowedVoters => allowed_voters
        votersVoted => voters_voted
        code => code
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
